# Generated by Django 3.2.3 on 2021-05-31 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={},
        ),
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
    ]
