# Generated by Django 3.2.3 on 2021-05-31 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_group_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
    ]
