# Generated by Django 3.2.3 on 2021-05-31 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_group_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='author',
        ),
    ]
